on: [pull_request]

name: Bench

jobs:
  bench_baseline:
    name: Bench
    runs-on: ubuntu-latest
    steps:
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Checkout repository base
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}

      - name: Run cargo bench on base
        run: cargo bench

      - name: Checkout repository head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          clean: false # Do not remove bench from base branch

      - name: Run cargo bench on head
        run: echo "::set-output name=result::$(cargo bench 2>&1)\n"
        id: bench_head

      - name: Comment on PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            Comparing base (`${{ github.base_ref }}` with HEAD (`${{ github.head_ref }}`).
            <details>
              <summary>Benchmark Results</summary>

              ```
              ${{ steps.bench_head.outputs.result }}
              ```
            </details>
          check_for_duplicate_msg: true
